language: node_js
sudo: false
node_js:
  - "8"
  - "6"

  before_install:
  - cd client
  - npm install
  - cd ../processor
  - npm install

  script:
  - cd client
  - npm test
  - cd ../processor
  - npm test

deploy:
  provider: npm
  email: npm@arundo.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master