language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

before_install:
  - cd client
  - npm install

script:
  - cd client
  - npm test
  - npm run release

deploy:
  provider: npm
  email: npm@arundo.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
