language: node_js

node_js:
  - "8"
 
  before_install:
  - cd client

  script:
  - npm test
  - cd ../processor
  - npm test

deploy:
  provider: npm
  email: npm@arundo.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
